version: '3'
services:
  web:
    stdin_open: true
    tty: true
    restart: always
    image: 213170096/nginx-php
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
      - ./config:/etc/nginx/sites-enabled